name = "main"
main = "_worker.js"
compatibility_date = "2024-01-01"

[vars]
UUID = "d1eaeb7e-c08f-4898-880e-411ac3e65dd3"
PROXYIP = "98.98.119.110"
DNS_RESOLVER_URL = "https://cloudflare-dns.com/dns-query"
